# Generated by Django 4.0.4 on 2022-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
    ]
