# Generated by Django 4.0.4 on 2022-05-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='license_plates',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
