# Generated by Django 4.0.4 on 2022-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_bus_license_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='arrived_time',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
    ]
