# Generated by Django 4.0.4 on 2022-05-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.bus'),
        ),
    ]
