# Generated by Django 4.0.4 on 2022-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='tags',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='buses', to='tickets.tag'),
        ),
    ]
