# Generated by Django 4.0.4 on 2022-05-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='subject',
        ),
    ]
